create table if not exists public.bid_after_sales_settings (
  id bigint generated by default as identity primary key,
  reference_number text not null unique,
  service_years integer not null default 1 check (service_years >= 1),
  warranty_years integer not null default 2 check (warranty_years >= 1),
  updated_at timestamptz not null default now()
);

alter table public.bid_after_sales_settings
add column if not exists warranty_years integer not null default 2
check (warranty_years >= 1);

alter table public.bid_after_sales_settings enable row level security;

drop policy if exists "Public can read after-sales settings"
on public.bid_after_sales_settings;
create policy "Public can read after-sales settings"
on public.bid_after_sales_settings for select
to anon, authenticated using (true);

drop policy if exists "Public can insert after-sales settings"
on public.bid_after_sales_settings;
create policy "Public can insert after-sales settings"
on public.bid_after_sales_settings for insert
to anon, authenticated with check (true);

drop policy if exists "Public can update after-sales settings"
on public.bid_after_sales_settings;
create policy "Public can update after-sales settings"
on public.bid_after_sales_settings for update
to anon, authenticated using (true) with check (true);

grant select, insert, update on public.bid_after_sales_settings
to anon, authenticated;
grant usage, select on sequence public.bid_after_sales_settings_id_seq
to anon, authenticated;
