create table if not exists public.bid_price_schedules (
  id bigint generated by default as identity primary key,
  reference_number text not null unique,
  total_prices_per_unit jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.bid_price_schedules enable row level security;

drop policy if exists "Public can read price schedules" on public.bid_price_schedules;
create policy "Public can read price schedules" on public.bid_price_schedules
for select to anon, authenticated using (true);

drop policy if exists "Public can insert price schedules" on public.bid_price_schedules;
create policy "Public can insert price schedules" on public.bid_price_schedules
for insert to anon, authenticated with check (true);

drop policy if exists "Public can update price schedules" on public.bid_price_schedules;
create policy "Public can update price schedules" on public.bid_price_schedules
for update to anon, authenticated using (true) with check (true);

grant select, insert, update on public.bid_price_schedules to anon, authenticated;
grant usage, select on sequence public.bid_price_schedules_id_seq to anon, authenticated;
