create table if not exists public.bid_schedule_requirements (
  id bigint generated by default as identity primary key,
  reference_number text not null unique,
  delivery_weeks_months text not null default '',
  updated_at timestamptz not null default now()
);

alter table public.bid_schedule_requirements enable row level security;

drop policy if exists "Public can read schedule requirements"
on public.bid_schedule_requirements;
create policy "Public can read schedule requirements"
on public.bid_schedule_requirements for select
to anon, authenticated using (true);

drop policy if exists "Public can insert schedule requirements"
on public.bid_schedule_requirements;
create policy "Public can insert schedule requirements"
on public.bid_schedule_requirements for insert
to anon, authenticated with check (true);

drop policy if exists "Public can update schedule requirements"
on public.bid_schedule_requirements;
create policy "Public can update schedule requirements"
on public.bid_schedule_requirements for update
to anon, authenticated using (true) with check (true);

grant select, insert, update on public.bid_schedule_requirements
to anon, authenticated;
grant usage, select on sequence public.bid_schedule_requirements_id_seq
to anon, authenticated;
