create table if not exists public.bid_slcc_entries (
  id bigint generated by default as identity primary key,
  reference_number text not null unique,
  owner_name text not null default '',
  address_telephone text not null default '',
  contact_number text not null default '',
  nature_of_work text not null default '',
  role_description text not null default '',
  role_percent text not null default '',
  amount_of_award text not null default '',
  completion_duration text not null default '',
  date_awarded text not null default '',
  contract_effectivity text not null default '',
  date_completed text not null default '',
  updated_at timestamptz not null default now()
);

alter table public.bid_slcc_entries enable row level security;

drop policy if exists "Public can read SLCC entries" on public.bid_slcc_entries;
create policy "Public can read SLCC entries"
on public.bid_slcc_entries
for select
to anon, authenticated
using (true);

drop policy if exists "Public can insert SLCC entries" on public.bid_slcc_entries;
create policy "Public can insert SLCC entries"
on public.bid_slcc_entries
for insert
to anon, authenticated
with check (true);

drop policy if exists "Public can update SLCC entries" on public.bid_slcc_entries;
create policy "Public can update SLCC entries"
on public.bid_slcc_entries
for update
to anon, authenticated
using (true)
with check (true);

grant select, insert, update on public.bid_slcc_entries to anon, authenticated;
grant usage, select on sequence public.bid_slcc_entries_id_seq to anon, authenticated;
