create table if not exists public.bid_technical_specifications (
  id bigint generated by default as identity primary key,
  reference_number text not null unique,
  specifications jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now()
);

-- Safe migration when the earlier compliance-only version already exists.
alter table public.bid_technical_specifications
add column if not exists specifications jsonb not null default '[]'::jsonb;

alter table public.bid_technical_specifications enable row level security;

drop policy if exists "Public can read technical specifications"
on public.bid_technical_specifications;
create policy "Public can read technical specifications"
on public.bid_technical_specifications
for select
to anon, authenticated
using (true);

drop policy if exists "Public can insert technical specifications"
on public.bid_technical_specifications;
create policy "Public can insert technical specifications"
on public.bid_technical_specifications
for insert
to anon, authenticated
with check (true);

drop policy if exists "Public can update technical specifications"
on public.bid_technical_specifications;
create policy "Public can update technical specifications"
on public.bid_technical_specifications
for update
to anon, authenticated
using (true)
with check (true);

grant select, insert, update on public.bid_technical_specifications
to anon, authenticated;
grant usage, select on sequence public.bid_technical_specifications_id_seq
to anon, authenticated;
